CREATE TABLE asset_rights_versions (
  id VARCHAR(96) NOT NULL,
  version BIGINT NOT NULL,
  organization_id VARCHAR(96) NOT NULL,
  project_id VARCHAR(96) NOT NULL,
  asset_id VARCHAR(96) NOT NULL,
  asset_version BIGINT NOT NULL,
  source VARCHAR(255) NOT NULL,
  rights_holder VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  derivative_work_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  generative_ai_allowed BOOLEAN NOT NULL DEFAULT FALSE,
  allowed_channels JSON NOT NULL,
  territories JSON NOT NULL,
  purposes JSON NOT NULL,
  valid_from DATETIME(6) NOT NULL,
  valid_until DATETIME(6) NULL,
  revoked_at DATETIME(6) NULL,
  asserted_by VARCHAR(255) NOT NULL,
  verified_by VARCHAR(255) NULL,
  evidence JSON NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id, version),
  UNIQUE KEY uq_asset_rights_version (organization_id, project_id, asset_id, asset_version, version),
  KEY idx_asset_rights_current (organization_id, project_id, asset_id, asset_version, version)
);
